### ISSUE TITLE
Create k8s yml files for different deployment strategies

### ISSUE THREAD

**Issue by Clivern** [Clivern/Toad#3]
**Issue** https://github.com/Clivern/Beetle/issues/12

**Ref:**
https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
https://www.weave.works/blog/kubernetes-deployment-strategies

**Ramped: release a new version on a rolling update fashion, one after the other.**

```yaml
spec:
  strategy:
        type: RollingUpdate
        rollingUpdate:
           maxSurge: 25%
           maxUnavailable: 25%  
```

**Recreate: terminate the old version and release the new one.**

```yaml
spec:
  strategy:
        type: Recreate
```
